### ISSUE TITLE
Unable to extract properties from source event

### ISSUE THREAD

**Issue by software-programmer** [datalust/seq-app-httprequest#4]
I seem to be unable to extract custom properties from the underlying event that caused the alert when using this app, yet I feel like I've followed the documents to a tee.

I want to extract the `Application` and `MachineName` from this simple event

## Event
![image](https://user-images.githubusercontent.com/5966776/146970058-e6fe069a-2e19-49b7-b2f7-1b2740b8fd78.png)

## App Instance
![image](https://user-images.githubusercontent.com/5966776/146969780-57de2150-d2ca-47ff-9112-9b70bbd6ae64.png)

## Alert Definition
![image](https://user-images.githubusercontent.com/5966776/146970320-9195e4ae-28aa-4576-8532-85945b83758d.png)

Yet I can't receive any of my custom properties

```
{
  "Message": "Alert condition triggered by admin/Healthcheck",
  "MessageTemplate": "Alert condition triggered by {NamespacedAlertTitle}",
  "Dictionary": {
    "@seqid": "event-50fa9bbbc4a408d90000000000000000",
    "NamespacedAlertTitle": "admin/Healthcheck",
    "Alert": {
      "Id": "alert-40",
      "Title": "Healthcheck",
      "Url": "http://localhost:80/#/alerts/alert-40",
      "OwnerUsername": "admin",
      "SignalExpressionDescription": null,
      "Query": "select count(*) as count from stream where functionName = 'Health' and status = 'Succeeded' group by time(1m) having count > 0 limit 100",
      "HavingClause": "count > 0",
      "TimeGrouping": "1 minute"
    },
    "Source": {
      "RangeStart": "2021-12-21T17:05:36.1917627Z",
      "RangeEnd": "2021-12-21T17:06:36.1917627Z",
      "ResultsUrl": "http://localhost:80/#/events?q=select%20count%28%2A%29%20as%20count%20from%20stream%20where%20functionName%20%3D%20%27Health%27%20and%20status%20%3D%20%27Succeeded%27%20group%20by%20time%281m%29%20having%20count%20%3E%200%20limit%20100&from=2021-12-21T17:05:36.1917627Z&to=2021-12-21T17:06:36.1917627Z",
      "Results": [
        [
          "time",
          "count"
        ],
        [
          "2021-12-21T17:05:36.1917627Z",
          4
        ]
      ],
      "ContributingEvents": [
        [
          "@Id",
          "(Column 2)",
          "@Message"
        ],
        [
          "event-2913c038c4a408d99cc2060000000000",
          "2021-12-21T17:05:59.2476728Z",
          "Executed 'Health' (Succeeded, Id=b026d54f-1bf8-40b1-bfd5-deb376336c6e, Duration=1ms)"
        ]
      ]
    },
    "SuppressedUntil": "2021-12-21T17:08:06.1917627Z",
    "Failures": null,
    "@i": "a1e77001"
  }
}
```

Is this something I've done wrong?

**Comment by liammclennan** [comment]
Hi Matt, 
You're not doing anything wrong. What you are trying to do is a little tricky with alerts, because alerts don't map to a single event (there may be many events that contribute to triggering an event). 

If what you want is to trigger a web request each time an event matches the condition there is a better way. Create a signal for functionName = 'Health' and status = 'Succeeded'. Create another instance of the Seq.App.HttpRequest app, select 'Stream incoming events' and choose the signal you created. 

That will reduce the input to a single event, and then I think your template should work. 

If you also want to see the alert triggered you can have an alert with no output app.

**Comment by software-programmer** [comment]
Great, thanks for the pointer. I'll give this a go.
